### ISSUE TITLE
Authentication popup not appearing for IOS, how can i use this library with ionic framework?

### ISSUE THREAD

**Issue by tarun57** [wsmd/musickit-typescript#1]
I'm using  this library in IONIC framework but i'm facing following problems:
1. In android opening authentication in browser and after login its not returning to the app with token.
2. Authentication not appearing in IOS app.

**Comment by wsmd** [comment]
Hi @tarun57 - It seems that the issue you're having might be related to the MusicKit JS framework itself and therefore this isn't the right place to discuss such issues. This repo is only concerned with the TypeScript type definitions of MusicKit JS.
